import { parseEmbroideryGcode } from '../../src/lib/embroideryPreview/parseEmbroideryGcode'

// What the TurtleStitch export writes per the beta6 contract: ';' comments,
// G1 X Y then G1 Z per stitch, a G0 jump with a lone G1 Z penetration at its
// end, a colour change as '; color' plus COLOR_CHANGE, M400 at the end.
const TURTLESTITCH = `; G-code generated by TurtleStitch
; Stitches: 5
; Size: 10.0mm x 10.0mm
; Color changes: 1
G21 ; millimeters
G90 ; absolute positioning
; color r:255 g:0 b:0
G0 X0.000 Y0.000
G1 Z5.000
G1 X10.000 Y0.000
G1 Z10.000
G1 X10.000 Y10.000
G1 Z15.000
; color r:0 g:0 b:255
COLOR_CHANGE
G0 X0.000 Y10.000
G1 Z20.000
G1 X0.000 Y0.000
G1 Z25.000
M400 ; wait for moves to finish
; Total Z travel: 25.0mm
`

// What Ink/Stitch writes: parenthesis comments, only G0, a Z-only line per
// stitch, M00 for a colour change, M30 at the end.
const INKSTITCH_BODY = `G90 (use absolute coordinates)
G21 (coordinates will be specified in millimeters)
G0 X5.000 Y5.000
G0 Z5.0
G0 X6.000 Y5.000
G0 Z10.0
M00
G0 X7.000 Y6.000
G0 Z15.0
G0 X8.000 Y6.000
G0 Z20.0
G0 X0.000 Y0.000
M30
`
const INKSTITCH = `(STITCH_COUNT:4)
(EXTENTS_LEFT:5.000)
(EXTENTS_BOTTOM:6.000)
${INKSTITCH_BODY}`

describe('Embroidery preview parser', () => {
    before(() => {
        // The same GCodeToGeometry build G-Code Studio loads at runtime.
        // It is a plain script that declares globals; run it and hand its
        // parser to this window, where the module under test looks for it.
        cy.readFile('src/lib/gcode2dviewer/gcodetogeometry.min.js').then((source: string) => {
            window.GCodeToGeometry = new Function(`${source}\nreturn GCodeToGeometry`)()
        })
    })

    it('needs the macro filter: GCodeToGeometry throws on a macro line', () => {
        const parser = window.GCodeToGeometry!
        expect(parser.parse('G90\nG1 X1 Y1 F1200').lines).to.have.length(1)
        expect(() => parser.parse('G90\nCOLOR_CHANGE\nG1 X1 Y1 F1200')).to.throw()
    })

    it('reads a multicolour TurtleStitch file', () => {
        const parsed = parseEmbroideryGcode(TURTLESTITCH, '#123456')
        expect(parsed).to.not.equal(null)
        if (!parsed) return

        expect(parsed.renderLines).to.have.length(5)
        expect(parsed.renderLines.map((line) => line.line.type)).to.deep.equal(['G0', 'G1', 'G1', 'G0', 'G1'])
        // G21: the parser works in inches and the result is scaled back
        expect(parsed.renderLines[2].line.end.x).to.be.closeTo(10, 1e-3)
        expect(parsed.renderLines[2].line.end.y).to.be.closeTo(10, 1e-3)
        // one Z step is one stitch: 5, not 5 Z lines plus 3 XY lines
        expect(parsed.stitchCount).to.equal(5)
        expect(parsed.jumpCount).to.equal(2)
        expect(parsed.treatG0AsStitch).to.equal(false)
        // '; color' and COLOR_CHANGE are one change
        expect(parsed.colorChangeIndices).to.deep.equal([0, 3])
        expect(parsed.hasColorChanges).to.equal(true)
        expect(parsed.renderLines.map((line) => line.color)).to.deep.equal([
            '#ff0000',
            '#ff0000',
            '#ff0000',
            '#0000ff',
            '#0000ff',
        ])
        // every move is followed by a penetration, the jump end too
        expect(parsed.stitchPointMoveIndices).to.deep.equal([0, 1, 2, 3, 4])
        expect(parsed.designWidth).to.be.closeTo(10, 1e-3)
        expect(parsed.designHeight).to.be.closeTo(10, 1e-3)
    })

    it('reads an Ink/Stitch file with a stitch count header', () => {
        const parsed = parseEmbroideryGcode(INKSTITCH)
        expect(parsed).to.not.equal(null)
        if (!parsed) return

        expect(parsed.renderLines).to.have.length(5)
        expect(parsed.treatG0AsStitch).to.equal(true)
        expect(parsed.jumpCount).to.equal(0)
        expect(parsed.stitchCount).to.equal(4)
        expect(parsed.colorChangeIndices).to.deep.equal([2])
        expect(parsed.stitchPointMoveIndices).to.deep.equal([0, 1, 2, 3])
    })

    it('counts the Z steps of an Ink/Stitch file without a header', () => {
        expect(parseEmbroideryGcode(INKSTITCH_BODY)?.stitchCount).to.equal(4)
    })

    it('keeps other macro and message lines away from the geometry parser', () => {
        const gcode = [
            'G90',
            'G21',
            'NEEDLE_TOGGLE',
            'G1 X1 Y1',
            'G1 Z5',
            'PAUSE',
            'M117 Rethread now',
            'STITCH',
            'LOCK_STITCH COUNT=3',
            'M600',
            'G1 X2 Y2',
            'G1 Z+5',
            'M400',
        ].join('\n')
        const parsed = parseEmbroideryGcode(gcode)
        expect(parsed).to.not.equal(null)
        expect(parsed?.renderLines).to.have.length(2)
        expect(parsed?.stitchCount).to.equal(2)
        expect(parsed?.colorChangeIndices).to.deep.equal([1])
    })
})
